# Generated by Django 5.1.4 on 2024-12-09 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luckyApp', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS luckyapp_lotteryhistory;
            CREATE TABLE luckyapp_lotteryhistory (
                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                draw_num VARCHAR(20) UNIQUE NOT NULL,
                red_ball_1 INTEGER NOT NULL,
                red_ball_2 INTEGER NOT NULL,
                red_ball_3 INTEGER NOT NULL,
                red_ball_4 INTEGER NOT NULL,
                red_ball_5 INTEGER NOT NULL,
                red_ball_6 INTEGER NOT NULL,
                blue_ball INTEGER NOT NULL,
                draw_date DATE NOT NULL,
                created_at DATETIME(6) NOT NULL
            );
            
            DROP TABLE IF EXISTS luckyapp_predictionrecord;
            CREATE TABLE luckyapp_predictionrecord (
                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                draw_num VARCHAR(20) NOT NULL,
                red_ball_1 INTEGER NOT NULL,
                red_ball_2 INTEGER NOT NULL,
                red_ball_3 INTEGER NOT NULL,
                red_ball_4 INTEGER NOT NULL,
                red_ball_5 INTEGER NOT NULL,
                red_ball_6 INTEGER NOT NULL,
                blue_ball INTEGER NOT NULL,
                prediction_type VARCHAR(20) NOT NULL,
                is_hit BOOLEAN NOT NULL,
                hit_count INTEGER NOT NULL,
                created_at DATETIME(6) NOT NULL
            );
            """
        )
    ]
