# Generated by Django 5.1.4
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('luckyApp', '0002_auto_20241209_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrecord',
            name='blue_hit',
            field=models.BooleanField(default=False, verbose_name='蓝球是否命中'),
        ),
    ] 