# Generated by Django 5.1.4 on 2024-12-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyApp', '0003_add_blue_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionrecord',
            name='draw_num',
            field=models.CharField(max_length=20, verbose_name='预测期��'),
        ),
    ]
